// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaavKygiGHPlC1ukYq5ClVk0YPlQ1Kkg',
    appId: '1:954137926104:web:f2ce6c9a91d0a25847baad',
    messagingSenderId: '954137926104',
    projectId: 'readymechanic-f07ca',
    authDomain: 'readymechanic-f07ca.firebaseapp.com',
    storageBucket: 'readymechanic-f07ca.firebasestorage.app',
    measurementId: 'G-M860060V3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pb6z_cWc7FDUwP3Te5bpPtp1DBI4O2g',
    appId: '1:954137926104:android:83fad9064170a2c347baad',
    messagingSenderId: '954137926104',
    projectId: 'readymechanic-f07ca',
    storageBucket: 'readymechanic-f07ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAX8eashNiYe-7DC5-2q5b2LpYRhl9Vt0',
    appId: '1:954137926104:ios:f791f6d5d7c1b26347baad',
    messagingSenderId: '954137926104',
    projectId: 'readymechanic-f07ca',
    storageBucket: 'readymechanic-f07ca.firebasestorage.app',
    iosClientId: '954137926104-t26lq3lgucnp4n2nuircosjaa68utf52.apps.googleusercontent.com',
    iosBundleId: 'com.example.readymechanic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAX8eashNiYe-7DC5-2q5b2LpYRhl9Vt0',
    appId: '1:954137926104:ios:f791f6d5d7c1b26347baad',
    messagingSenderId: '954137926104',
    projectId: 'readymechanic-f07ca',
    storageBucket: 'readymechanic-f07ca.firebasestorage.app',
    iosClientId: '954137926104-t26lq3lgucnp4n2nuircosjaa68utf52.apps.googleusercontent.com',
    iosBundleId: 'com.example.readymechanic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNaavKygiGHPlC1ukYq5ClVk0YPlQ1Kkg',
    appId: '1:954137926104:web:a99642c9c3a28eaa47baad',
    messagingSenderId: '954137926104',
    projectId: 'readymechanic-f07ca',
    authDomain: 'readymechanic-f07ca.firebaseapp.com',
    storageBucket: 'readymechanic-f07ca.firebasestorage.app',
    measurementId: 'G-K4D85ZTGMV',
  );

}