// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoBSj-lrPFEGZINtKc1zMRA0uxAwkOkQ',
    appId: '1:1032238559305:web:adab2ee9f3a81f79dccf98',
    messagingSenderId: '1032238559305',
    projectId: 'mechanic-1b1ff',
    authDomain: 'mechanic-1b1ff.firebaseapp.com',
    storageBucket: 'mechanic-1b1ff.firebasestorage.app',
    measurementId: 'G-3F9ECH9QWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgF24_7x1qokxJvwvGXhoJnUhtcyWN7nw',
    appId: '1:1032238559305:android:393a201db029debcdccf98',
    messagingSenderId: '1032238559305',
    projectId: 'mechanic-1b1ff',
    storageBucket: 'mechanic-1b1ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDD7JqYnEsmR1RjfsrDNzFZcXDrK7Gpn4',
    appId: '1:1032238559305:ios:0714db7e99a808ffdccf98',
    messagingSenderId: '1032238559305',
    projectId: 'mechanic-1b1ff',
    storageBucket: 'mechanic-1b1ff.firebasestorage.app',
    iosBundleId: 'com.example.readymechanic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDD7JqYnEsmR1RjfsrDNzFZcXDrK7Gpn4',
    appId: '1:1032238559305:ios:0714db7e99a808ffdccf98',
    messagingSenderId: '1032238559305',
    projectId: 'mechanic-1b1ff',
    storageBucket: 'mechanic-1b1ff.firebasestorage.app',
    iosBundleId: 'com.example.readymechanic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoBSj-lrPFEGZINtKc1zMRA0uxAwkOkQ',
    appId: '1:1032238559305:web:676f0c62e1ab5144dccf98',
    messagingSenderId: '1032238559305',
    projectId: 'mechanic-1b1ff',
    authDomain: 'mechanic-1b1ff.firebaseapp.com',
    storageBucket: 'mechanic-1b1ff.firebasestorage.app',
    measurementId: 'G-VNEBX1J3ZP',
  );
}
